# Path to a list of domains to match
# Currently IDN domains are not supported
domains = "/var/cache/rkn_domains.txt"

# Path to a BoltDB file where to persist the cache
# Optional
cache = "/var/cache/dnstap-bgp.db"

# TTL of the entries in cache
# If the entry is not requested by clients for this duration the it's purged from the cache
ttl = "24h"

[dnstap]
# Path to a DNSTap socket
socket = "/tmp/dnstap.sock"

# Permissions which are set on the socket file
perm = "0666"

[bgp]
# BGP AS
as = 65000

# BGP router ID
routerID = "192.168.111.1"

# Source IP to use when establishing BGP peering (optional)
sourceIP = "192.168.113.1"

# BGP nexthop (optional)
# If not defined - the SourceIP will be used
# It it's also not defined - then RouterID
nextHop = "192.168.112.1"

# List of BGP peers
peers = [
    "192.168.0.1",
    "192.168.0.2:177",
]

[syncer]
# Where to listen for sync requests
listen = "0.0.0.0:8080"

# Sync peers
peers = [
    "192.168.0.2:8080",
]
